from .FedAvg import FedAvg
from .FedProx import FedProx
from .FedALA import FedALA
from .FedPolyak import FedPolyak
from .LocalOnly import LocalOnly
from .Central import Central
from .FedAtt import FedAtt
from .FedCAC import FedCAC
from .FedBABU import FedBABU